# Update all the sections by editing the data.yml file inside _data folder.

# Site Settings

# SEO plugin
title: N. Rombach
author: Nicholas Rombach
tagline: Design Engineer # Short description for jekyll-seo-tag
description: Resume for a design engineer, tooling engineer, controls engineer, automation engineer, specializing in solidworks and PLC programming # Longer description for jekyll-seo-tag

url: "https://nrhartfrc.github.io" # sub a landing page
baseurl: "/resume" # repo name

# twitter:
#   username: stevedoe123
#   card: summary

social:
  links:
    # - https://twitter.com/stevedoe123
    # - https://www.facebook.com/stevedoe123
    - https://www.linkedin.com/in/nicholasrombach/
    - https://github.com/NRHartFRC/
    # - https://keybase.io/stevedoe123

google_site_verification: d7fhemCkj1XcDCdssxNqG6LHnTwJF74PAMUv2ccTmIg # google verification tag content

# End SEO

# Style will be applied only after restarting the build or serve.
theme_skin: turquoise # gray blue turquoise green berry red

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
